@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

Class "{abstract}\nCommand" as Command
Class SearchCommand

package "Parser classes" {
    Class "<<interface>>\nParser" as Parser
    Class AddressBookParser
    Class SearchCommandParser
    Class CliSyntax
    Class ParserUtil
    Class ArgumentMultimap
    Class ArgumentTokenizer
    Class Prefix
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> AddressBookParser

AddressBookParser .down.> SearchCommandParser : <<create>>

SearchCommandParser ..> SearchCommand : <<create>>
AddressBookParser ..> Command : <<use>>
SearchCommandParser .up.|> Parser
SearchCommandParser ..> ArgumentMultimap
SearchCommandParser ..> ArgumentTokenizer
ArgumentTokenizer .left.> ArgumentMultimap
SearchCommandParser ..> CliSyntax
CliSyntax ..> Prefix
SearchCommandParser ..> ParserUtil
ParserUtil .down.> Prefix
ArgumentTokenizer .down.> Prefix
SearchCommand -up-|> Command
@enduml
